# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

shorttitle: DI-CPS 2023
title: The 3rd Workshop on Data-Driven and Intelligent Cyber-Physical Systems for Smart Cities (DI-CPS)
email: rahul.bhadani@vanderbilt.edu
author:
  name: Rahul Bhadani
  about:

location: San Antonio, Texas USA
date: May 9, 2023

description: >- # this means to ignore newlines until "baseurl:"
  After a successful DI-CPS workshop at CPS-IoT Week 2022, we are back with the third iteration of the workshop.
  This year, our focus is on Data-Driven and Intelligent Cyber-Physical Systems for urban computing related to but not limited to intelligent transportation, smart cities, and smart-grid. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

background: |
  <p>Smart cities are emerging as a priority for Cyber-Physical Systems (CPS) research and development across the world. Artificial Intelligence and Machine Learning algorithms have played a large part in automating and advancing city operations and aiding the development of CPS in cities. Increasingly, data-driven modeling and intelligent decision-making under uncertainty are forming the basis for advancing transportation, safety, connectivity, and health services. For example, advanced traffic solutions, improved public transportation systems, smart emergency response, energy modeling, and autonomous driving are some of the applications that have benefited from data-driven approaches to principled decision-making. Data is extremely valuable in determining human behavior both at the scale of the entire population as well as at the level of individual persons navigating the infrastructure landscape. </p><br/>
  

  <p>With the advent of Internet of Things (IoT), sensor data is being generated at a pace and volume that is difficult to process and use for inference. With several data modalities in the picture, new opportunities and challenges arise in terms of data collection, validation, analysis, and inference. For example, these additional data enable the development of novel models of traffic behavior at different geographical locations and time points, as well as what factors are consequential human driving behavior. At the same time, there is a growing need for automated applications to be fair, secure, and resilient. Participants in the workshop will exchange ideas on these and allied topics, including data science and open-source data sets for smart cities, decision making for smart cities, design of intelligent systems in smart cities, and challenges in deployment, equity, and fairness in smart cities, as well as security and privacy in AI for cities. </p><br/>
  
  
  <p>The Workshop on Data-Driven and Intelligent Cyber-Physical Systems (DI-CPS) was started in 2021 in conjunction with CPS-IoT Week. After a successful workshop this year, we seek to continue the workshop at CPS-week next year, albeit with a specific focus on intelligent CPS for smart cities. The 2020 edition of DI-CPS received 10 submissions and had a total attendance of approximately 30. This year, we are also introducing a best paper award based on reviewer scores. Also, in addition to having experienced faculty members as part of the PC, we are nominating senior graduate students to the PC to provide them with experience in participating in program committees of academic events. Papers assigned to graduate students will have an extra reviewer chosen from the senior members of the PC. The workshop invites researchers and practitioners from academia, industry, and government to submit original research papers, papers describing lessons learned, concept papers, or descriptions of software tools on the following categories:</p><br/>

  <p>1. Approaches to modeling complex decision-making tasks in smart cities and tackling uncertainty.</p>
  <p>2. Challenges faced and lessons learned in deploying intelligent systems in smart cities in practice.</p>
  <p>3. Principled heuristics to design scalable decision-making in city-scale CPS.</p>
  <p>4. Anomaly detection in smart and connected communities.</p>
  <p>5. Trustworthy analytics and privacy control.</p>
  <p>6. Transportation CPS data with human-in-the-loop.</p>
  <p>7. Demos and tutorials on software tools, simulations, and experimental results concerning CPS with a human-in-the-loop in the context of smart cities.</p>
  <p>8. Software tools for integrative analysis of data-driven CPS from multiple modalities.</p>
  
submission_guidelines: |
  <p>We welcome long papers (8 pages), short papers (4 pages), and concept papers (2 pages) including appendices and references. Submissions must use the IEEE conference format. Only PDF or latex-zipped files will be accepted. There is no requirement to anonymize the submissions; Authors may choose to submit anonymously or not. Accepted papers will be published with IEEE and appear on IEEE Xplore; however, authors can choose to opt out of formal proceedings. We welcome prior work published in conferences or journals (authors will have to opt out of publication in case the submitted work does not add to the previously published version, but can still present their work at the workshop). Each accepted paper must be presented by a registered author. Submissions not meeting these guidelines risk immediate rejection. For questions about these policies, please contact the chairs.</p>


important_dates: |
  <p>Paper Submission Deadline: February 1, 2023 (23:59 Anywhere on Earth time)</p>
  <p>Notification of Acceptance/Rejection: February 28, 2023</p>
  <p>Camera-Ready Papers Due: (hard deadline): March 7, 2023</p>

program_chairs: |
  <p>Rahul Bhadani (Vanderbilt University) rahul.bhadani@vanderbilt.edu</p>
  <p>Aron Laszka (Pennsylvania State University) laszka@psu.edu</p>
  <p>Ayan Mukhopadhyay (Vanderbilt University) ayan.mukhopadhyay@vanderbilt.edu</p>
  <p>Raphael Stern (University of Minnesota) rstern@umn.edu</p>
  
contacts:
  # - title: twitter 
  #  url: 'https://twitter.com/whyherro1'
  # - title: github
  #  url:  'https://github.com/nativvstudios'
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  # - title: instagram
  #   url: 'https://example.com/@jekyllrb'
  # - title: linkedin
  #   url: 'https://example.com/@jekyllrb'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: email
    url: mailto:rahul.bhadani@vanderbilt.edu
    email: rahul.bhadani@vanderbilt.edu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
