# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

shorttitle: DI-CPS 2023
title: The 3rd Workshop on Data-Driven and Intelligent Cyber-Physical Systems for Smart Cities (DI-CPS)
email: rahul.bhadani@vanderbilt.edu
author:
  name: Rahul Bhadani
  about:

location: San Antonio, Texas USA
date: May 9, 2023
submission_link: https://easychair.org/conferences/?conf=dicps23

description: >- # this means to ignore newlines until "baseurl:"
  After successfully hosting the DI-CPS workshop at CPS-IoT Week 2022, we are back with its third iteration.
  This year, our focus is on Data-Driven and Intelligent Cyber-Physical Systems for urban computing related to but not limited to intelligent transportation, smart cities, and smart-grid. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

schedule: |

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-l38m{background-color:#FFF;border-color:inherit;text-align:right;vertical-align:top}
.tg .tg-rp7u{background-color:#4DD0E1;border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-jxgv{background-color:#FFF;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-0xrc{background-color:#E0F7FA;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-rvuo{border-color:inherit;color:#434343;font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-z115{background-color:#cbcefb;border-color:inherit;text-align:right;vertical-align:top}
.tg .tg-61xu{background-color:#cbcefb;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-vppv{background-color:#E0F7FA;border-color:inherit;text-align:right;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-rvuo" colspan="5"><span style="color:#434343">DI CPS 2023 Schedule</span></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-rp7u">Sequence</td>
    <td class="tg-rp7u">Time</td>
    <td class="tg-rp7u">Time Duration</td>
    <td class="tg-rp7u">Title</td>
    <td class="tg-rp7u">Authors</td>
  </tr>
  <tr>
    <td class="tg-z115">0</td>
    <td class="tg-61xu">12 pm – 1:30 pm</td>
    <td class="tg-61xu">30 minutes</td>
    <td class="tg-61xu">Lunch Break</td>
    <td class="tg-61xu"></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">1</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">1:30 pm&nbsp;&nbsp;– 1:45 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">15 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Opening Remark</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">DI-CPS Chairs</span></td>
  </tr>
  <tr>
    <td class="tg-l38m"><span style="background-color:#FFF">2</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">1:45 pm&nbsp;&nbsp;–&nbsp;&nbsp;2:30 pm</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">45 minutes</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Keynote</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">TBD</span></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">3</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">2:40 pm&nbsp;&nbsp;– 3:00 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">20 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Physics-informed Machine Learning </span><br><span style="background-color:#E0F7FA">Model Generalization in AIoT: Opportunites and Challenges	</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Wenjie Luo and Rui Tan</span></td>
  </tr>
  <tr>
    <td class="tg-z115">4</td>
    <td class="tg-61xu">3:00 pm – 3:20pm</td>
    <td class="tg-61xu">20 minutes</td>
    <td class="tg-61xu">Break</td>
    <td class="tg-61xu"></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">5</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">3:20 pm&nbsp;&nbsp;– 3:40 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">20 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Dynamic Simplex: Balancing Safety and </span><br><span style="background-color:#E0F7FA">Performance in Autonomous Cyber Physical Systems	</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Baiting Luo, Shreyas Ramakrishna, Ava Pettet, </span><br><span style="background-color:#E0F7FA">Christopher Kuhn, Gabor Karsai and Ayan Mukhopadhyay	</span></td>
  </tr>
  <tr>
    <td class="tg-l38m"><span style="background-color:#FFF">6</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">3:40 pm – 4:00 pm</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">20 minutes</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Assessing the Impact of Disruptive Events </span><br><span style="background-color:#FFF">on Urban Mobility: A Case Study of Chicago Taxis during COVID-19	</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Tianyi Li, Xiatian Iogansen and Raphael Stern</span></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">7</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">4:00 pm&nbsp;&nbsp;– 4:20 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">20 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Intelligent Distributed Charging Control for Large </span><br><span style="background-color:#E0F7FA">Scale Electric Vehicles: A Multi-Cluster Mean Field Game Approach</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Shawon Dey and Hao Xu</span></td>
  </tr>
  <tr>
    <td class="tg-61xu"></td>
    <td class="tg-61xu">4:20 pm - 4: 35 pm </td>
    <td class="tg-61xu">15 minutes</td>
    <td class="tg-61xu">Break</td>
    <td class="tg-61xu"></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">8</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">4:35 pm&nbsp;&nbsp;– 4:55 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">20 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Visualization of Large-Scale Trajectory Datasets</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Gergely Zachar</span></td>
  </tr>
  <tr>
    <td class="tg-l38m"><span style="background-color:#FFF">9</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">4:55 pm&nbsp;&nbsp;–&nbsp;&nbsp;5:15 pm</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">20 minutes</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Analysis of a Runtime Data Sharing </span><br><span style="background-color:#FFF">Architecture over LTE for a Heterogeneous CAV Fleet	</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Alex Richardson, Matthew Nice, Matthew Bunting, </span><br><span style="background-color:#FFF">Jonathan Lee, Rahul Bhadani, Dan Work and Jonathan Sprinkle</span></td>
  </tr>
  <tr>
    <td class="tg-vppv"><span style="background-color:#E0F7FA">10</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">5:15 pm&nbsp;&nbsp;–&nbsp;&nbsp;5:35 pm</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">20 minutes</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Approaches for Synthesis and Deployment of </span><br><span style="background-color:#E0F7FA">Controller Models on Automated Vehicles for Car-following in Mixed Autonomy</span></td>
    <td class="tg-0xrc"><span style="background-color:#E0F7FA">Rahul Bhadani, Matt Bunting, Matthew Nice, Fangyu Wu, </span><br><span style="background-color:#E0F7FA">Amaury Hayat, Jonathan Lee, Alexandre Bayen, Benedetto Piccoli, </span><br><span style="background-color:#E0F7FA">Benjamin Seibold, Dan Work and Jonathan Sprinkle</span></td>
  </tr>
  <tr>
    <td class="tg-l38m"><span style="background-color:#FFF">11</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">5:35 pm&nbsp;&nbsp;–&nbsp;&nbsp;5:40 pm</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">5 minutes</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">Concluding Remarks</span></td>
    <td class="tg-jxgv"><span style="background-color:#FFF">DI-CPS Chairs</span></td>
  </tr>
</tbody>
</table>


background: |
  <p>Smart cities are emerging as a priority for Cyber-Physical Systems (CPS) research and development across the world. Artificial Intelligence and Machine Learning algorithms have played a large part in automating and advancing city operations and aiding the development of CPS in cities. Increasingly, data-driven modeling and intelligent decision-making under uncertainty are forming the basis for advancing transportation, safety, connectivity, and health services. For example, advanced traffic solutions, improved public transportation systems, smart emergency response, energy modeling, and autonomous driving are some of the applications that have benefited from data-driven approaches to principled decision-making. Data is extremely valuable in determining human behavior both at the scale of the entire population as well as at the level of individual persons navigating the infrastructure landscape. </p><br/>
  

  <p>With the advent of Internet of Things (IoT), sensor data is being generated at a pace and volume that is difficult to process and use for inference. With several data modalities in the picture, new opportunities and challenges arise in terms of data collection, validation, analysis, and inference. For example, these additional data enable the development of novel models of traffic behavior at different geographical locations and time points, as well as what factors are consequential human driving behavior. At the same time, there is a growing need for automated applications to be fair, secure, and resilient. Participants in the workshop will exchange ideas on these and allied topics, including data science and open-source data sets for smart cities, decision making for smart cities, design of intelligent systems in smart cities, and challenges in deployment, equity, and fairness in smart cities, as well as security and privacy in AI for cities. </p><br/>
  
  
  <p>The Workshop on Data-Driven and Intelligent Cyber-Physical Systems (DI-CPS) was started in 2021 in conjunction with CPS-IoT Week. After a successful workshop this year, we seek to continue the workshop at CPS-week next year, albeit with a specific focus on intelligent CPS for smart cities. The 2020 edition of DI-CPS received 10 submissions and had a total attendance of approximately 30. This year, we are also introducing a best paper award based on reviewer scores. Also, in addition to having experienced faculty members as part of the PC, we are nominating senior graduate students to the PC to provide them with experience in participating in program committees of academic events. Papers assigned to graduate students will have an extra reviewer chosen from the senior members of the PC. The workshop invites researchers and practitioners from academia, industry, and government to submit original research papers, papers describing lessons learned, concept papers, or descriptions of software tools on the following categories:</p><br/>

  <p>1. Approaches to modeling complex decision-making tasks in smart cities and tackling uncertainty.</p>
  <p>2. Challenges faced and lessons learned in deploying intelligent systems in smart cities in practice.</p>
  <p>3. Principled heuristics to design scalable decision-making in city-scale CPS.</p>
  <p>4. Anomaly detection in smart and connected communities.</p>
  <p>5. Trustworthy analytics and privacy control.</p>
  <p>6. Transportation CPS data with human-in-the-loop.</p>
  <p>7. Demos and tutorials on software tools, simulations, and experimental results concerning CPS with a human-in-the-loop in the context of smart cities.</p>
  <p>8. Software tools for integrative analysis of data-driven CPS from multiple modalities.</p>
  
submission_guidelines: |
  <p>Paper should be within 6 pages including appendices and references following the ACM format. Only PDF files will be accepted. There is no requirement to anonymize the submissions; Authors may choose to submit anonymously or not but true anonymity is not guaranteed. Accepted papers will be published as ACM proceedings; however, authors can choose to opt-out of formal proceedings. We welcome prior work published in conferences or journals (authors will have to opt-out of publication in case the submitted work does not add to the previously published version, but can still present their work at the workshop). Each accepted paper must be presented by a registered author. Submissions not meeting these guidelines risk immediate rejection. For questions about these policies, please contact the chairs.</p>

  <p><br/><b>Additional Guidelines</b></p>
  <p>1. "By submitting your article to an ACM Publication, you are hereby acknowledging that you and your co-authors are subject to all <a href="https://www.acm.org/publications/policies" style="color: #BB2649; text-decoration: underline; font-weight: bold;">ACM Publications Policies</a>, including ACM's new <a href="https://www.acm.org/publications/policies/research-involving-human-participants-and-subjects" style="color: #BB2649; text-decoration: underline; font-weight: bold;">Publications Policy on Research Involving Human Participants and Subjects</a>. Alleged violations of this policy or any ACM Publications Policy will be investigated by ACM and may result in a full retraction of your paper, in addition to other potential penalties, as per ACM Publications Policy. Please see <a href="https://www.acm.org/publications/policies/research-involving-human-participants-and-subjects" style="color: #BB2649; text-decoration: underline; font-weight: bold;">https://www.acm.org/publications/policies/research-involving-human-participants-and-subjects</a>.</p>

  <p>2. "Please ensure that you and your co-authors obtain an <a href="https://orcid.org/register" style="color: #BB2649; text-decoration: underline; font-weight: bold;">ORCID ID</a>, so you can complete the publishing process for your accepted paper. ACM has been involved in ORCID from the start and we have recently made a commitment to collect ORCID IDs from all of our published authors. The collection process has started and will roll out as a requirement throughout 2022. We are committed to improve author discoverability, ensure proper attribution and contribute to ongoing community efforts around name normalization; your ORCID ID will help in these efforts."</p>

important_dates: |
  <p>Paper Submission Deadline: February 22, 2023 (23:59 Anywhere on Earth time)</p>
  <p>Notification of Acceptance/Rejection: March 4, 2023</p>
  <p>Camera-Ready Papers Due: (hard deadline): March 7, 2023</p>

program_chairs: |
  <p>Rahul Bhadani (Vanderbilt University) rahul.bhadani@vanderbilt.edu</p>
  <p>Aron Laszka (Pennsylvania State University) laszka@psu.edu</p>
  <p>Ayan Mukhopadhyay (Vanderbilt University) ayan.mukhopadhyay@vanderbilt.edu</p>
  <p>Raphael Stern (University of Minnesota) rstern@umn.edu</p>
  
contacts:
  # - title: twitter 
  #  url: 'https://twitter.com/whyherro1'
  # - title: github
  #  url:  'https://github.com/nativvstudios'
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  # - title: instagram
  #   url: 'https://example.com/@jekyllrb'
  # - title: linkedin
  #   url: 'https://example.com/@jekyllrb'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: email
    url: mailto:rahul.bhadani@vanderbilt.edu
    email: rahul.bhadani@vanderbilt.edu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
